app.url=http://172.23.176.163:8200/
app.login=http://172.23.176.163:8200/web/index.php/auth/login
app.auth=http://172.23.176.163:8200/web/index.php/auth/validate
app.dashboard=http://172.23.176.163:8200/web/index.php/dashboard/index
app.buzzboard=http://172.23.176.163:8200/web/index.php/buzz/viewBuzz
app.updatePassword=http://172.23.176.163:8200/web/index.php/pim/updatePassword
browser=chrome
#valid login
Username=Perf-User
Password=Perf-User123
NewPassword=Perf-User321
AdminUser=admin
AdminPassword=AdminPass1!