url=https://parabank.parasoft.com/parabank/index.htm
login.url=https://parabank.parasoft.com/parabank/login.htm
register.url=https://parabank.parasoft.com/parabank/register.htm

browser=chrome
#valid login
Username=Perf-User
Password=Perf-User123